import { useEffect, useMemo, useState } from 'react';
import { Search, SlidersHorizontal, ExternalLink, ShoppingBag, Store, Languages, ChevronRight } from 'lucide-react';

type Product={id:string;name:string;price:number;currency?:string;image?:string;url?:string;merchantUrl?:string;merchant?:string;brand?:string;category?:string;description?:string;inStock?:string;ean?:string;sku?:string;model?:string};
type StoreMeta={name:string;count:number}; type Payload={products?:Product[];meta?:{stores?:StoreMeta[]}}; type Lang='ru'|'lv';
const API=import.meta.env.VITE_FEED_API_URL||'https://cenaradar-feed-api.onrender.com/api/products';
const norm=(s='')=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\p{L}\p{N}]+/gu,' ').trim();
const money=(n:number,c='EUR')=>{try{return new Intl.NumberFormat('lv-LV',{style:'currency',currency:c}).format(n)}catch{return `${n.toFixed(2)} ${c}`}};
const groups=[
 ['all','Все товары','Visas preces',['']],
 ['fashion','Одежда и обувь','Apģērbs un apavi',['apģērb','apgerb','kleit','biks','jaka','mētel','metel','krek','blūz','bluz','džemper','dzemper','apav','kurp','zābak','zabak','soma','fashion','dress','shirt','pants','shoe','clothing']],
 ['tools','Инструменты','Instrumenti',['instrument','tools','urbj','zāģ','zag','skrūv','skruv','bosch','makita','dewalt']],
 ['auto','Авто','Auto',['auto','riep','carplay','automotive','disk','motoreļ','motorel']],
 ['electronics','Электроника','Elektronika',['telefon','smartphone','iphone','samsung','xiaomi','laptop','dator','tv','audio','headphone','ssd','playstation','gaming']],
 ['home','Дом и сад','Māja un dārzs',['māja','maja','dārz','darz','mēbel','mebel','home','garden','vacuum']],
 ['sport','Спорт и отдых','Sports un atpūta',['sport','fitness','velo','bike','camp','outdoor']],
 ['pets','Животным','Mājdzīvniekiem',['pet','suņ','sun','kaķ','kak','dzīvniek']],
 ['beauty','Красота и здоровье','Skaistums un veselība',['beauty','kosmēt','kosmet','health','vitam','šamp','samp','cream']],
 ['fishing','Рыбалка','Makšķerēšana',['makšķ','maksk','fishing','cope','spining','ēsma','esma']],
] as const;
const txt={ru:{tag:'СРАВНЕНИЕ ЦЕН В ЛАТВИИ',title:'Все товары. Все цены. Один поиск.',sub:'Ищи по единому каталогу CenaRadar — магазин выбираешь только тогда, когда нашёл нужную цену.',ph:'Название, бренд, модель, EAN…',find:'Найти',cat:'Категории',found:'Найдено',store:'Магазин',brand:'Бренд',stock:'Только в наличии',clear:'Сбросить',to:'В магазин',stores:'Подключённые магазины',all:'Все',sort:'Сортировка',relevance:'По релевантности',cheap:'Сначала дешевле',expensive:'Сначала дороже',more:'Показать ещё',none:'Ничего не найдено — измени запрос или фильтры.',filters:'Фильтры',loading:'Загрузка каталога…',unavailable:'Магазин временно недоступен',products:'товаров',shops:'магазинов'},lv:{tag:'CENU SALĪDZINĀŠANA LATVIJĀ',title:'Visas preces. Visas cenas. Viena meklēšana.',sub:'Meklē vienotajā CenaRadar katalogā — veikalu izvēlies tikai tad, kad atrasta vajadzīgā cena.',ph:'Nosaukums, zīmols, modelis, EAN…',find:'Meklēt',cat:'Kategorijas',found:'Atrasts',store:'Veikals',brand:'Zīmols',stock:'Tikai pieejamās',clear:'Notīrīt',to:'Uz veikalu',stores:'Pieslēgtie veikali',all:'Visi',sort:'Kārtošana',relevance:'Pēc atbilstības',cheap:'Lētākie vispirms',expensive:'Dārgākie vispirms',more:'Rādīt vēl',none:'Nekas nav atrasts — maini vaicājumu vai filtrus.',filters:'Filtri',loading:'Katalogs tiek ielādēts…',unavailable:'Veikals īslaicīgi nav pieejams',products:'preces',shops:'veikali'}};
const hay=(p:Product)=>norm(`${p.name} ${p.brand||''} ${p.model||''} ${p.ean||''} ${p.sku||''} ${p.category||''} ${p.description||''}`);
const inGroup=(p:Product,key:string)=>key==='all'||!!groups.find(g=>g[0]===key)?.[3].some(k=>hay(p).includes(norm(k)));
const score=(p:Product,q:string)=>{const n=norm(q);if(!n)return 0;const name=norm(p.name),brand=norm(p.brand),model=norm(p.model),ean=norm(p.ean),h=hay(p);let s=0;if(name===n)s+=100;if(ean===n||model===n)s+=90;if(name.startsWith(n))s+=50;if(name.includes(n))s+=35;if(brand===n)s+=25;for(const token of n.split(' ').filter(Boolean)){if(name.includes(token))s+=10;else if(h.includes(token))s+=3}return s};
export default function AggregatorApp(){
 const [lang,setLang]=useState<Lang>(()=>localStorage.getItem('cenaradar:lang')==='lv'?'lv':'ru'); const t=txt[lang];
 const [products,setProducts]=useState<Product[]>([]),[stores,setStores]=useState<StoreMeta[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(false);
 const [q,setQ]=useState(''),[activeQ,setActiveQ]=useState(''),[group,setGroup]=useState('all'),[store,setStore]=useState(''),[brand,setBrand]=useState(''),[stock,setStock]=useState(false),[sort,setSort]=useState('relevance'),[limit,setLimit]=useState(48);
 useEffect(()=>{localStorage.setItem('cenaradar:lang',lang)},[lang]);
 useEffect(()=>{const c=new AbortController();fetch(API,{signal:c.signal,headers:{Accept:'application/json'}}).then(r=>{if(!r.ok)throw Error(String(r.status));return r.json()}).then((p:Payload)=>{setProducts(p.products||[]);setStores(p.meta?.stores||[]);setError(false)}).catch(e=>{if(e?.name!=='AbortError')setError(true)}).finally(()=>setLoading(false));return()=>c.abort()},[]);
 const brands=useMemo(()=>Array.from(new Set(products.map(p=>p.brand).filter(Boolean) as string[])).sort().slice(0,300),[products]);
 const counts=useMemo(()=>Object.fromEntries(groups.map(g=>[g[0],products.filter(p=>inGroup(p,g[0])).length])),[products]);
 const filtered=useMemo(()=>{const tokens=norm(activeQ).split(' ').filter(Boolean);let x=products.filter(p=>{const h=hay(p);if(tokens.length&&!tokens.every(k=>h.includes(k)))return false;if(!inGroup(p,group))return false;if(store&&p.merchant!==store)return false;if(brand&&p.brand!==brand)return false;if(stock&&['0','false','no','out of stock'].includes(String(p.inStock||'').toLowerCase()))return false;return true});if(sort==='cheap')x=[...x].sort((a,b)=>a.price-b.price);else if(sort==='expensive')x=[...x].sort((a,b)=>b.price-a.price);else if(activeQ)x=[...x].sort((a,b)=>score(b,activeQ)-score(a,activeQ)||a.price-b.price);return x},[products,activeQ,group,store,brand,stock,sort]);
 const submit=()=>{setActiveQ(q.trim());setLimit(48)}; const reset=()=>{setQ('');setActiveQ('');setGroup('all');setStore('');setBrand('');setStock(false);setSort('relevance');setLimit(48)};
 return <div className="ag-app"><header className="ag-head"><a href="#top" className="ag-logo"><img src="/favicon.svg"/>Cena<span>Radar</span></a><nav><a href="#catalog">{t.cat}</a><a href="#shops">{t.stores}</a></nav><div className="ag-lang"><Languages size={15}/><button className={lang==='lv'?'on':''} onClick={()=>setLang('lv')}>LV</button><button className={lang==='ru'?'on':''} onClick={()=>setLang('ru')}>RU</button></div></header><main id="top">
 <section className="ag-hero"><b>{t.tag}</b><h1>{t.title}</h1><p>{t.sub}</p><div className="ag-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&submit()} placeholder={t.ph}/><button onClick={submit}>{t.find}</button></div><small>{products.length.toLocaleString()} {t.products} · {stores.length} {t.shops}</small></section>
 <section className="ag-wrap"><h2>{t.cat}</h2><div className="ag-cats">{groups.map(g=><button key={g[0]} className={group===g[0]?'on':''} onClick={()=>{setGroup(g[0]);setLimit(48)}}>{lang==='ru'?g[1]:g[2]} <small>{counts[g[0]]||0}</small><ChevronRight size={14}/></button>)}</div></section>
 <section className="ag-wrap ag-catalog" id="catalog"><aside className="ag-filters"><h3><SlidersHorizontal size={17}/>{t.filters}</h3><label>{t.store}<select value={store} onChange={e=>setStore(e.target.value)}><option value="">{t.all}</option>{stores.map(s=><option key={s.name}>{s.name} ({s.count})</option>)}</select></label><label>{t.brand}<select value={brand} onChange={e=>setBrand(e.target.value)}><option value="">{t.all}</option>{brands.map(b=><option key={b}>{b}</option>)}</select></label><label>{t.sort}<select value={sort} onChange={e=>setSort(e.target.value)}><option value="relevance">{t.relevance}</option><option value="cheap">{t.cheap}</option><option value="expensive">{t.expensive}</option></select></label><label className="ag-check"><input type="checkbox" checked={stock} onChange={e=>setStock(e.target.checked)}/>{t.stock}</label><button className="ag-reset" onClick={reset}>{t.clear}</button></aside><div className="ag-results"><div className="ag-results-head"><h2>{t.found}: {filtered.length.toLocaleString()}</h2>{activeQ&&<span>“{activeQ}”</span>}</div>{loading?<div className="ag-empty">{t.loading}</div>:error?<div className="ag-empty">API недоступен. Каталог будет восстановлен после ответа сервера.</div>:filtered.length===0?<div className="ag-empty">{t.none}</div>:<div className="ag-grid">{filtered.slice(0,limit).map(p=>{const u=p.merchantUrl||p.url;const broken=(p.merchant||'').toLowerCase().includes('vilders');return <article className="ag-card" key={`${p.merchant}-${p.id}`}><div className="ag-img">{p.image?<img src={p.image} loading="lazy" onError={e=>e.currentTarget.style.display='none'}/>:<ShoppingBag/>}</div><div className="ag-shop">{p.merchant||'Store'}</div><h3>{p.name}</h3><div className="ag-meta">{p.brand&&<span>{p.brand}</span>}{p.category&&<span>{p.category}</span>}</div><div className="ag-buy"><strong>{money(p.price,p.currency)}</strong>{u&&!broken?<a href={u} target="_blank" rel="noreferrer">{t.to}<ExternalLink size={13}/></a>:<button disabled title={broken?t.unavailable:undefined}>{broken?t.unavailable:t.to}</button>}</div></article>})}</div>}{limit<filtered.length&&<button className="ag-more" onClick={()=>setLimit(v=>v+48)}>{t.more}</button>}</div></section>
 <section className="ag-wrap ag-shops" id="shops"><h2>{t.stores}</h2><div>{stores.map(s=><span key={s.name}><Store size={16}/><b>{s.name}</b><small>{s.count.toLocaleString()}</small></span>)}</div></section></main><footer>© 2026 CenaRadar · cenaradar.online</footer></div>
}