import http from 'node:http';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { searchConfiguredMerchantFeeds } from './merchant-feeds.mjs';
import { getTradedoublerStatus, searchTradedoublerProducts, tradedoublerConfigured } from './tradedoubler-products.mjs';
const PORT=Number(process.env.PORT||10000),CACHE_MS=Number(process.env.FEED_CACHE_MS||10*60*1000);const here=dirname(fileURLToPath(import.meta.url));const ALLOWED=new Set(['https://cenaradar.online','https://www.cenaradar.online','https://cenaradar.onrender.com']);let cache=null,refresh=null;
const norm=(v='')=>String(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\p{L}\p{N}]+/gu,' ').trim();
const GROUPS={fashion:['apģērb','apgerb','kleit','biks','jaka','apav','fashion','dress','shirt','pants','shoe'],tools:['instrument','tools','urbj','zāģ','zag','bosch','makita','dewalt'],auto:['auto','riep','tyre','tire','carplay','automotive','disk','motoreļ','motorel'],electronics:['telefon','iphone','samsung','xiaomi','laptop','dator','tv','audio','ssd'],home:['māja','maja','dārz','darz','mēbel','mebel','home','garden'],sport:['sport','fitness','velo','bike','camp','outdoor'],pets:['pet','suņ','sun','kaķ','kak','dzīvniek'],beauty:['beauty','kosmēt','kosmet','health','vitam','šamp','samp','cream'],fishing:['makšķ','maksk','fishing','cope','spining','ēsma','esma']};
const hay=p=>norm([p.name,p.brand,p.model,p.mpn,p.ean,p.sku,p.category,p.description,p.merchant].filter(Boolean).join(' '));function inGroup(p,g){if(!g||g==='all')return true;if(g==='auto'&&p.merchant==='RigasRiepas.lv')return true;return (GROUPS[g]||[]).some(k=>hay(p).includes(norm(k)))}function categoryCounts(products){const out={all:products.length};for(const g of Object.keys(GROUPS))out[g]=products.reduce((n,p)=>n+(inGroup(p,g)?1:0),0);return out}
function matches(p,q){const n=norm(q);if(!n)return true;const h=hay(p);return n.split(' ').filter(Boolean).every(t=>h.includes(t))}function dedupe(items){const seen=new Set(),out=[];for(const p of items||[]){if(!p?.name||!Number.isFinite(Number(p.price))||Number(p.price)<=0)continue;const k=`${p.merchant||''}|${p.url||p.merchantUrl||p.id||p.sku||p.name}`;if(seen.has(k))continue;seen.add(k);out.push(p)}return out}function storesFrom(products){const m=new Map();for(const p of products){const n=p.merchant||'Unknown';m.set(n,(m.get(n)||0)+1)}return [...m].map(([name,count])=>({name,count,mode:name==='RigasRiepas.lv'?'snapshot':'feed'})).sort((a,b)=>b.count-a.count)}
function loadRigas(){try{const raw=JSON.parse(readFileSync(join(here,'snapshots','rigasriepas.json'),'utf8'));const rows=Array.isArray(raw)?raw:Array.isArray(raw.products)?raw.products:[];return rows.map((p,i)=>({...p,id:String(p.id||p.sku||p.ean||`rigas-${i}`),merchant:'RigasRiepas.lv',currency:p.currency||'EUR',url:p.url||p.merchantUrl||'',merchantUrl:p.merchantUrl||p.url||'',category:p.category||'Riepas'}))}catch(e){console.error(`Rigas snapshot failed: ${e.message}`);return[]}}
async function loadOttocast(){try{const r=await fetch('https://www.ottocast.com/products.json?limit=250',{signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error(`HTTP ${r.status}`);const j=await r.json();return (j.products||[]).map(p=>{const v=(p.variants||[]).map(v=>({...v,n:Number(v.price)})).filter(v=>v.n>0).sort((a,b)=>a.n-b.n)[0];if(!v)return null;const u=`https://www.ottocast.com/products/${encodeURIComponent(p.handle)}`;return{id:String(p.id),name:p.title,price:v.n,currency:'USD',image:p.image?.src||'',url:u,merchantUrl:u,merchant:'Ottocast',brand:p.vendor||'Ottocast',sku:v.sku||'',category:p.product_type||'Automotive electronics'}}).filter(Boolean)}catch{return[]}}
async function build(){const [mf,ottocast,td]=await Promise.all([searchConfiguredMerchantFeeds('',100000),loadOttocast(),getTradedoublerStatus()]);const rigas=loadRigas(),products=dedupe([...(mf.products||[]),...rigas,...ottocast]),stores=storesFrom(products);return{products,meta:{fetchedAt:new Date().toISOString(),live:products.length>0,productCount:products.length,storeCount:stores.length,stores,categoryCounts:categoryCounts(products),sources:[...(mf.sources||[]),...(rigas.length?[{name:'RigasRiepas.lv',ok:true,count:rigas.length}]:[]),...(td.sources||[])],tradedoublerConfigured:td.configured}}}
async function getProducts(){if(cache&&Date.now()-cache.at<CACHE_MS)return cache.data;if(refresh)return refresh;refresh=build().then(data=>(cache={at:Date.now(),data},data)).finally(()=>refresh=null);return refresh}
function page(c,u){const q=(u.searchParams.get('q')||'').trim(),group=u.searchParams.get('group')||'all',offset=Math.max(0,Number(u.searchParams.get('offset')||0)),limit=Math.min(96,Math.max(1,Number(u.searchParams.get('limit')||48)));let base=q?c.products.filter(p=>matches(p,q)):c.products;const counts=categoryCounts(base);let rows=group==='all'?base:base.filter(p=>inGroup(p,group));return{products:rows.slice(offset,offset+limit),meta:{...c.meta,categoryCounts:counts,productCount:rows.length,totalProductCount:c.products.length,offset,limit,hasMore:offset+limit<rows.length}}}
function cors(req,res){const o=req.headers.origin;if(o&&ALLOWED.has(o)){res.setHeader('Access-Control-Allow-Origin',o);res.setHeader('Vary','Origin')}res.setHeader('Access-Control-Allow-Methods','GET, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type')}function send(res,status,payload){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','public, max-age=60, stale-while-revalidate=300');res.end(JSON.stringify(payload))}
const server=http.createServer(async(req,res)=>{cors(req,res);if(req.method==='OPTIONS'){res.statusCode=204;return res.end()}const u=new URL(req.url||'/','http://localhost');try{if(req.method==='GET'&&u.pathname==='/health'){const p=await getProducts();return send(res,200,{ok:true,cachedProducts:p.products.length,storeCount:p.meta.storeCount,stores:p.meta.stores,categoryCounts:p.meta.categoryCounts})}if(req.method==='GET'&&u.pathname==='/api/catalog')return send(res,200,page(await getProducts(),u));if(req.method==='GET'&&u.pathname==='/api/search')return send(res,200,page(await getProducts(),new URL(`/x?q=${encodeURIComponent(u.searchParams.get('q')||'')}`,'http://x')));if(req.method==='GET'&&u.pathname==='/api/products')return send(res,200,await getProducts());return send(res,404,{error:'Not found'})}catch(e){console.error(e);return send(res,500,{error:e.message||'Server error'})}});server.listen(PORT,'0.0.0.0',()=>{console.log(`CenaRadar feed API listening on ${PORT}`);void getProducts().then(p=>console.log(`Product warmup: ${p.products.length} products, stores=${p.meta.storeCount}`))});
