import http from 'node:http';
import { readFileSync } from 'node:fs';
import { dirname,join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { searchConfiguredMerchantFeeds } from './merchant-feeds.mjs';
import { getTradedoublerStatus,tradedoublerConfigured } from './tradedoubler-products.mjs';
const PORT=Number(process.env.PORT||10000),CACHE_MS=Number(process.env.FEED_CACHE_MS||600000),here=dirname(fileURLToPath(import.meta.url));const ALLOWED=new Set(['https://cenaradar.online','https://www.cenaradar.online','https://cenaradar.onrender.com']);let cache=null,refresh=null;
const norm=(v='')=>String(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\p{L}\p{N}]+/gu,' ').trim();
const KEYS={fashion:['apgerb','drebes','kleita','bikses','jaka','krekls','apavi','dress','shirt','pants','shoes','clothing','tom tailor'],tools:['instrument','urbis','urbj','zagis','slipmasina','skruvgriezis','makita','bosch','dewalt'],auto:['riepa','riepas','tyre','tire','auto diski','wheel rim','automasin','automotive'],phones:['telefons','smartphone','iphone','samsung galaxy','xiaomi redmi','pixel'],computers:['dators','laptop','notebook','macbook','procesors','ryzen','intel core','ssd','videokarte','monitor'],audio:['austinas','headphones','earbuds','skaļrunis','skalrunis','audio','sony wh'],tv:['televizors','smart tv','tv box','tv pristavka','projector'],gaming:['nintendo','playstation','xbox','gaming','speļu','spelu'],home:['mebeles','gulta','skapis','virtuve','puteklu sucejs','puteklsucejs','gaisa sausinatajs','humidifier','dehumidifier'],garden:['darza','garden','zales plavejs','trimmeris','granulas','briketes'],sport:['sporta','fitness','trenazieris','treadmill','dumbbell'],cycling:['velosipeds','bicycle','cycling','velo'],outdoor:['teltis','camping','outdoor','pargajiens'],pets:['majdzivniek','sunim','suniem','kakim','kakiem','pet food','dog food','cat food'],beauty:['kosmetika','skaistums','sejas krems','body cream','smarzas','parfums'],health:['vitamini','supplement','health care','asinsspiediena','termometrs'],fishing:['makskere','makskeresana','spining','zveja','fishing rod','fishing reel','esma'],baby:['berniem','mazuliem','baby','stroller','rati'],office:['biroja','office','printeris','printer','papirs'],construction:['buvniec','cement','flizes','santehnika','radiators'],other:[]};
const ORDER=['fishing','pets','baby','beauty','health','fashion','phones','computers','gaming','audio','tv','home','garden','cycling','sport','outdoor','construction','auto','tools','office'];const phrase=(h,k)=>` ${h} `.includes(` ${norm(k)} `);
function classify(p,h){const m=norm(p.merchant||''),cat=norm(p.category||'');if(m==='rigasriepas lv')return'auto';if(m==='eg tools')return'tools';if(m==='ottocast')return'auto';if(m==='valenas lv')return'fashion';const text=`${cat} ${h}`;for(const g of ORDER)if(KEYS[g].some(k=>phrase(text,k)))return g;return'other'}
function decorate(p){const h=norm([p.name,p.brand,p.model,p.mpn,p.ean,p.sku,p.category,p.description].filter(Boolean).join(' '));return{...p,_h:h,_g:classify(p,h)}}function counts(rows){const o={all:rows.length};for(const g of Object.keys(KEYS))o[g]=0;for(const p of rows)o[p._g]=(o[p._g]||0)+1;return o}function clean(p){const{_h,_g,...x}=p;return{...x,cenaRadarCategory:_g}}function dedupe(items){const s=new Set(),o=[];for(const p of items||[]){if(!p?.name||!(Number(p.price)>0))continue;const k=`${p.merchant||''}|${p.url||p.merchantUrl||p.id||p.sku||p.name}`;if(!s.has(k)){s.add(k);o.push(decorate(p))}}return o}function storesFrom(ps){const m=new Map();for(const p of ps)m.set(p.merchant||'Unknown',(m.get(p.merchant||'Unknown')||0)+1);return[...m].map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count)}
function loadRigas(){try{const raw=JSON.parse(readFileSync(join(here,'snapshots','rigasriepas.json'),'utf8')),rows=Array.isArray(raw)?raw:raw.products||[];return rows.map((p,i)=>({...p,id:String(p.id||p.sku||p.ean||`rigas-${i}`),merchant:'RigasRiepas.lv',currency:p.currency||'EUR',url:p.url||p.merchantUrl||'',merchantUrl:p.merchantUrl||p.url||'',category:p.category||'Riepas'}))}catch{return[]}}
async function loadOttocast(){try{const r=await fetch('https://www.ottocast.com/products.json?limit=250',{signal:AbortSignal.timeout(12000)});if(!r.ok)return[];const j=await r.json();return(j.products||[]).map(p=>{const v=(p.variants||[]).map(v=>({...v,n:Number(v.price)})).filter(v=>v.n>0).sort((a,b)=>a.n-b.n)[0];if(!v)return null;const u=`https://www.ottocast.com/products/${encodeURIComponent(p.handle)}`;return{id:String(p.id),name:p.title,price:v.n,currency:'USD',image:p.image?.src||'',url:u,merchantUrl:u,merchant:'Ottocast',brand:p.vendor||'Ottocast',sku:v.sku||'',category:p.product_type||'Automotive electronics'}}).filter(Boolean)}catch{return[]}}
async function build(){const[mf,ottocast,td]=await Promise.all([searchConfiguredMerchantFeeds('',100000),loadOttocast(),getTradedoublerStatus()]);const products=dedupe([...(mf.products||[]),...loadRigas(),...ottocast]),stores=storesFrom(products),categoryCounts=counts(products);console.log(`Catalog ready ${products.length}; ${JSON.stringify(categoryCounts)}`);return{products,meta:{productCount:products.length,storeCount:stores.length,stores,categoryCounts,fetchedAt:new Date().toISOString(),tradedoublerConfigured:td.configured}}}async function getProducts(){if(cache&&Date.now()-cache.at<CACHE_MS)return cache.data;if(refresh)return refresh;refresh=build().then(data=>(cache={at:Date.now(),data},data)).finally(()=>refresh=null);return refresh}

function modelKey(p){const strong=norm(p.ean||p.gtin||p.mpn||p.model||'');if(strong&&strong.length>=5)return strong;const brand=norm(p.brand||'');let name=norm(p.name||'').replace(/\b(black|white|red|blue|green|silver|melns|balts|sarkans|zils|zalš|zals)\b/g,' ').replace(/\s+/g,' ').trim();return norm(brand+' '+name).slice(0,140)}
function groupModels(rows){const map=new Map();for(const p of rows){const k=modelKey(p)||norm(p.merchant+' '+p.id);let x=map.get(k);if(!x){x={...clean(p),offers:[],offerCount:0,minPrice:Number(p.price)};map.set(k,x)}x.offers.push({merchant:p.merchant||'Store',price:Number(p.price),currency:p.currency||'EUR',url:p.merchantUrl||p.url||''});x.offerCount=x.offers.length;if(Number(p.price)<x.minPrice){x.minPrice=Number(p.price);x.price=p.price;x.currency=p.currency;x.merchant=p.merchant;x.url=p.url;x.merchantUrl=p.merchantUrl}}for(const x of map.values())x.offers.sort((a,b)=>a.price-b.price);return[...map.values()].sort((a,b)=>a.minPrice-b.minPrice)}
function page(c,u){const q=norm(u.searchParams.get('q')||''),group=u.searchParams.get('group')||'all',offset=Math.max(0,Number(u.searchParams.get('offset')||0)),limit=Math.min(96,Math.max(1,Number(u.searchParams.get('limit')||48))),tokens=q.split(' ').filter(Boolean);const base=tokens.length?c.products.filter(p=>tokens.every(t=>p._h.includes(t))):c.products,categoryCounts=tokens.length?counts(base):c.meta.categoryCounts,rows=group==='all'?base:base.filter(p=>p._g===group),models=groupModels(rows);return{products:models.slice(offset,offset+limit),meta:{...c.meta,categoryCounts,productCount:models.length,rawProductCount:rows.length,totalProductCount:c.products.length,offset,limit,hasMore:offset+limit<models.length}}}
function cors(req,res){const o=req.headers.origin;if(o&&ALLOWED.has(o)){res.setHeader('Access-Control-Allow-Origin',o);res.setHeader('Vary','Origin')}res.setHeader('Access-Control-Allow-Methods','GET, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type')}function send(res,status,p){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(p))}const server=http.createServer(async(req,res)=>{cors(req,res);if(req.method==='OPTIONS'){res.statusCode=204;return res.end()}const u=new URL(req.url||'/','http://localhost');try{if(req.method==='GET'&&u.pathname==='/health'){const p=await getProducts();return send(res,200,{ok:true,cachedProducts:p.products.length,storeCount:p.meta.storeCount,stores:p.meta.stores,categoryCounts:p.meta.categoryCounts,tradedoublerConfigured:tradedoublerConfigured()})}if(req.method==='GET'&&u.pathname==='/api/catalog')return send(res,200,page(await getProducts(),u));return send(res,404,{error:'Not found'})}catch(e){console.error(e);return send(res,500,{error:e.message||'Server error'})}});server.listen(PORT,'0.0.0.0',()=>{console.log(`CenaRadar API ${PORT}`);void getProducts()});
