import http from 'node:http';
import { readFileSync } from 'node:fs';
import { dirname,join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { searchConfiguredMerchantFeeds } from './merchant-feeds.mjs';
import { getTradedoublerStatus,tradedoublerConfigured } from './tradedoubler-products.mjs';
const PORT=Number(process.env.PORT||10000),CACHE_MS=Number(process.env.FEED_CACHE_MS||600000),MAX_LIMIT=Number(process.env.API_MAX_LIMIT||400),here=dirname(fileURLToPath(import.meta.url));const ALLOWED=new Set(['https://cenaradar.online','https://www.cenaradar.online','https://cenaradar.onrender.com']);let cache=null,refresh=null;const rigasBoot=loadRigas(),quickBoot=rigasBoot.slice(0,25000);
const norm=(v='')=>String(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\p{L}\p{N}]+/gu,' ').trim();
const KEYS={fashion:['apgerb','drebes','kleita','bikses','jaka','krekls','apavi','dress','shirt','pants','shoes','clothing','tom tailor','cimdi','zabaki','zekes'],tools:['instrument','urbis','urbj','zagis','slipmasina','skruvgriezis','makita','bosch','dewalt'],auto:['riepa','riepas','tyre','tire','auto diski','wheel rim','automasin','automotive','cilindra','gultnu','remkomplekts','sajuga','daksas','blivju','virzula','amortizatora','blivslegu','bremzu','trosite','suporta','zobrata','iepludes','amortizacijas','stures','varsts','varstu','klanis','filtrs','sadales','kede','izpludes','ellas','moto'],phones:['telefons','smartphone','iphone','samsung galaxy','xiaomi redmi','pixel'],computers:['dators','laptop','notebook','macbook','procesors','ryzen','intel core','ssd','videokarte','monitor'],audio:['austinas','headphones','earbuds','skaļrunis','skalrunis','audio','sony wh'],tv:['televizors','smart tv','tv box','tv pristavka','projector'],gaming:['nintendo','playstation','xbox','gaming','speļu','spelu'],home:['mebeles','gulta','skapis','virtuve','puteklu sucejs','puteklsucejs','gaisa sausinatajs','humidifier','dehumidifier'],garden:['darza','garden','zales plavejs','trimmeris','granulas','briketes'],sport:['sporta','fitness','trenazieris','treadmill','dumbbell'],cycling:['velosipeds','bicycle','cycling','velo'],outdoor:['teltis','camping','outdoor','pargajiens'],pets:['majdzivniek','sunim','suniem','kakim','kakiem','pet food','dog food','cat food'],beauty:['kosmetika','skaistums','sejas krems','body cream','smarzas','parfums'],health:['vitamini','supplement','health care','asinsspiediena','termometrs'],fishing:['makskere','makskeresana','spining','zveja','fishing rod','fishing reel','esma'],baby:['berniem','mazuliem','baby','stroller','rati'],office:['biroja','office','printeris','printer','papirs'],construction:['buvniec','cement','flizes','santehnika','radiators'],other:[]};
const MERCHANT_GROUPS={'rigasriepas lv':'auto','eg tools':'tools','ottocast':'auto','valenas lv':'fashion'};const ORDER=['fishing','pets','baby','beauty','health','fashion','phones','computers','gaming','audio','tv','home','garden','cycling','sport','outdoor','construction','auto','tools','office'];const phrase=(h,k)=>` ${h} `.includes(` ${norm(k)} `);
function classify(p,h){const m=norm(p.merchant||''),cat=norm(p.category||''),fixed=MERCHANT_GROUPS[m];if(fixed)return fixed;const catHits=[];for(const g of ORDER)if(KEYS[g].some(k=>phrase(cat,k)))catHits.push(g);if(catHits.length)return catHits[0];for(const g of ORDER)if(KEYS[g].some(k=>phrase(h,k)))return g;return'other'}
function decorate(p){const h=norm([p.name,p.brand,p.model,p.mpn,p.ean,p.sku,p.category,p.description].filter(Boolean).join(' '));return{...p,_h:h,_g:classify(p,h)}}function counts(rows){const o={all:rows.length};for(const g of Object.keys(KEYS))o[g]=0;for(const p of rows)o[p._g]=(o[p._g]||0)+1;return o}function clean(p){const{_h,_g,...x}=p;return{...x,cenaRadarCategory:_g}}function dedupe(items){const s=new Set(),o=[];for(const p of items||[]){if(!p?.name||!(Number(p.price)>0))continue;const k=`${p.merchant||''}|${p.url||p.merchantUrl||p.id||p.sku||p.name}`;if(!s.has(k)){s.add(k);o.push(decorate(p))}}return o}function storesFrom(ps){const m=new Map();for(const p of ps)m.set(p.merchant||'Unknown',(m.get(p.merchant||'Unknown')||0)+1);return[...m].map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count)}
function loadRigas(){try{const raw=JSON.parse(readFileSync(join(here,'snapshots','rigasriepas.json'),'utf8')),rows=Array.isArray(raw)?raw:raw.products||[];return rows.map((p,i)=>({...p,id:String(p.id||p.sku||p.ean||`rigas-${i}`),merchant:'RigasRiepas.lv',currency:p.currency||'EUR',url:p.url||p.merchantUrl||'',merchantUrl:p.merchantUrl||p.url||'',category:p.category||'Riepas'}))}catch{return[]}}
async function loadOttocast(){try{const r=await fetch('https://www.ottocast.com/products.json?limit=250',{signal:AbortSignal.timeout(12000)});if(!r.ok)return[];const j=await r.json();return(j.products||[]).map(p=>{const v=(p.variants||[]).map(v=>({...v,n:Number(v.price)})).filter(v=>v.n>0).sort((a,b)=>a.n-b.n)[0];if(!v)return null;const u=`https://www.ottocast.com/products/${encodeURIComponent(p.handle)}`;return{id:String(p.id),name:p.title,price:v.n,currency:'USD',image:p.image?.src||'',url:u,merchantUrl:u,merchant:'Ottocast',brand:p.vendor||'Ottocast',sku:v.sku||'',category:p.product_type||'Automotive electronics'}}).filter(Boolean)}catch{return[]}}
function pack(products,extra={}){const stores=storesFrom(products),categoryCounts=counts(products);return{products,meta:{productCount:products.length,storeCount:stores.length,stores,categoryCounts,fetchedAt:new Date().toISOString(),...extra}}}cache={at:Date.now(),data:pack(dedupe(quickBoot),{warming:true})};async function build(){const[mf,ottocast,td]=await Promise.all([searchConfiguredMerchantFeeds('',100000),loadOttocast(),getTradedoublerStatus()]);const products=dedupe([...(mf.products||[]),...rigasBoot,...ottocast]);const data=pack(products,{warming:false,tradedoublerConfigured:td.configured});console.log(`Catalog ready ${products.length}; ${JSON.stringify(data.meta.categoryCounts)}`);const otherCats={};for(const p of products)if(p._g==='other'){const k=String(p.category||'Uncategorized').trim()||'Uncategorized';otherCats[k]=(otherCats[k]||0)+1}console.log(`Other taxonomy top ${JSON.stringify(Object.entries(otherCats).sort((a,b)=>b[1]-a[1]).slice(0,25))}`);const otherTerms={};for(const p of products)if(p._g==='other')for(const t of norm(`${p.brand||''} ${p.name||''}`).split(' ').filter(x=>x.length>=4)){otherTerms[t]=(otherTerms[t]||0)+1}console.log(`Other terms top ${JSON.stringify(Object.entries(otherTerms).sort((a,b)=>b[1]-a[1]).slice(0,40))}`);const smoke=['автотовары','auto preces','automotive','инструменты','instrumenti','tools','одежда','apģērbs','clothing','шины','riepas','tires'].map(q=>[q,queryGroup(q)?products.filter(p=>p._g===queryGroup(q)).length:products.filter(p=>matchesQuery(p,q)).length]);console.log(`Search smoke ${JSON.stringify(smoke)}`);return data}async function getProducts(){return cache.data}async function refreshProducts(){if(refresh)return refresh;refresh=build().then(data=>(cache={at:Date.now(),data},data)).catch(e=>{console.error('Catalog refresh failed; keeping last good catalog',e);return cache.data}).finally(()=>refresh=null);return refresh}



const SYN={
 'шуруповерт':['шуруповерт','шуруповёрт','screwdriver','drill driver','impact driver','skruvgriezis','urbjmasina','urbjmašīna'],
 'шуруповёрт':['шуруповерт','шуруповёрт','screwdriver','drill driver','impact driver','skruvgriezis','urbjmasina','urbjmašīna'],
 'дрель':['дрель','drill','urbis','urbjmašīna'],'пила':['пила','saw','zāģis','zagis'],'болгарка':['болгарка','grinder','angle grinder','slīpmašīna'],
 'трусы':['трусы','underwear','briefs','boxers','apakšveļa'],'носки':['носки','socks','zeķes'],'обувь':['обувь','shoes','apavi'],'платье':['платье','dress','kleita'],'штаны':['штаны','брюки','pants','bikses'],
 'телефон':['телефон','phone','smartphone','telefons'],'смартфон':['смартфон','smartphone','phone','telefons'],'ноутбук':['ноутбук','laptop','notebook','portatīvais dators'],'наушники':['наушники','headphones','earbuds','austiņas'],
 'шины':['шины','резина','tyres','tires','riepas'],'диски':['диски','rims','wheels','diski'],'пылесос':['пылесос','vacuum','putekļsūcējs'],
 'автотовары':['riepa','riepas','tyre','tire','auto','automotive','carplay','ottocast'],'авто товары':['riepa','riepas','tyre','tire','auto','automotive','carplay','ottocast'],
 'одежда':['apģērbs','drēbes','clothing','dress','shirt','pants','jaka','krekls','bikses'],'инструменты':['instrumenti','tools','makita','bosch','dewalt','urbis','drill','saw','zāģis'],
 'генератор':['генератор','generator','ģenerators'],'генераторы':['генераторы','generator','ģenerators'],'игровые консоли':['игровые консоли','game console','gaming console','nintendo','playstation','xbox','spēļu konsole'],
 'riepas':['riepas','tires','tyres','шины'],'tires':['tires','tyres','riepas','шины'],'apģērbs':['apģērbs','drēbes','clothing','одежда'],'clothing':['clothing','apģērbs','drēbes','одежда'],
 'instrumenti':['instrumenti','tools','инструменты','makita','bosch','dewalt'],'tools':['tools','instrumenti','инструменты','makita','bosch','dewalt'],
 'telefons':['telefons','phone','smartphone','телефон'],'phone':['phone','smartphone','telefons','телефон'],'smartphone':['smartphone','phone','telefons','смартфон'],
 'portatīvais dators':['portatīvais dators','laptop','notebook','ноутбук'],'laptop':['laptop','notebook','portatīvais dators','ноутбук'],
 'austiņas':['austiņas','headphones','earbuds','наушники'],'headphones':['headphones','earbuds','austiņas','наушники'],
 'auto preces':['auto preces','automotive','riepas','carplay','автотовары'],'automotive':['automotive','auto preces','riepas','carplay','автотовары']
};
const GROUP_QUERY={
 'автотовары':'auto','авто товары':'auto','auto preces':'auto','automotive':'auto',
 'инструменты':'tools','instrumenti':'tools','tools':'tools',
 'одежда':'fashion','одежда и обувь':'fashion','apģērbs':'fashion','apgerbs':'fashion','drēbes':'fashion','drebes':'fashion','clothing':'fashion'
};
function queryGroup(q){return GROUP_QUERY[norm(q)]||''}
function queryTerms(q){const n=norm(q),out=new Set(n.split(' ').filter(Boolean));for(const [k,vs] of Object.entries(SYN))if(n.includes(norm(k)))for(const v of vs)out.add(norm(v));return[...out]}
function matchesQuery(p,q){if(!q)return true;const n=norm(q),phraseAlts=SYN[n];if(phraseAlts)return phraseAlts.some(a=>p._h.includes(norm(a)));const original=n.split(' ').filter(Boolean);return original.every(t=>{const alts=SYN[t]||[t];return alts.some(a=>p._h.includes(norm(a)))})}
function scoreQuery(p,q){const n=norm(q);if(!n)return 0;let s=0;if(norm(p.ean||'')===n||norm(p.model||'')===n||norm(p.mpn||'')===n)s+=100;if(norm(p.name||'').includes(n))s+=50;if(norm(p.brand||'')===n)s+=20;for(const t of queryTerms(q))if(p._h.includes(t))s+=2;return s}

const SUB={auto:[['tires',['riepa','riepas','tyre','tire']],['wheels',['diski','wheel rim','rims']],['electronics',['dash cam','carplay','android auto','ottocast']],['parts',['rezerves dalas','auto parts','spare parts','cilindra','gultnu','remkomplekts','sajuga','daksas','blivju','virzula','amortizatora','blivslegu','bremzu','trosite','suporta','zobrata','iepludes','amortizacijas','stures','varsts','klanis']],['care',['auto kopšana','car care','autokimija']]],tools:[['drills',['urbis','urbj','drill']],['saws',['zagis','saw']],['grinders',['slipmasina','grinder']],['fastening',['skruvgriezis','screwdriver','impact driver']],['measuring',['merinstrument','measure','laser level']],['accessories',['filtrs','filter','adapter','akumulators','battery']]],fashion:[['shoes',['apavi','shoes','boots']],['dresses',['kleita','dress']],['pants',['bikses','pants']],['tops',['krekls','shirt','jaka','jacket']]],computers:[['laptops',['laptop','notebook','macbook']],['monitors',['monitor']],['components',['procesors','ryzen','intel core','ssd','videokarte']]],home:[['cleaning',['puteklu sucejs','puteklsucejs','vacuum']],['climate',['gaisa sausinatajs','humidifier','dehumidifier']],['furniture',['mebeles','gulta','skapis']]],audio:[['headphones',['austinas','headphones','earbuds']],['speakers',['skalrunis','speaker']]],gaming:[['playstation',['playstation']],['xbox',['xbox']],['nintendo',['nintendo']]]};
function subFor(p){const hay=norm(`${p.category||''} ${p._h||''}`);for(const [id,ks] of SUB[p._g]||[])if(ks.some(k=>phrase(hay,k)))return id;return'other'}function subCounts(rows){const o={};for(const p of rows){const s=subFor(p);o[s]=(o[s]||0)+1}return o}
function modelKey(p){const strong=norm(p.ean||p.gtin||p.mpn||p.model||'');if(strong&&strong.length>=5)return strong;const brand=norm(p.brand||'');let name=norm(p.name||'').replace(/\b(black|white|red|blue|green|silver|melns|balts|sarkans|zils|zalš|zals)\b/g,' ').replace(/\s+/g,' ').trim();return norm(brand+' '+name).slice(0,140)}
function groupModels(rows){const map=new Map();for(const p of rows){const k=modelKey(p)||norm(p.merchant+' '+p.id);let x=map.get(k);if(!x){x={...clean(p),offers:[],offerCount:0,minPrice:Number(p.price)};map.set(k,x)}x.offers.push({merchant:p.merchant||'Store',price:Number(p.price),currency:p.currency||'EUR',url:p.merchantUrl||p.url||''});x.offerCount=x.offers.length;if(Number(p.price)<x.minPrice){x.minPrice=Number(p.price);x.price=p.price;x.currency=p.currency;x.merchant=p.merchant;x.url=p.url;x.merchantUrl=p.merchantUrl}}for(const x of map.values())x.offers.sort((a,b)=>a.price-b.price);return[...map.values()].sort((a,b)=>a.minPrice-b.minPrice)}
function page(c,u){const q=norm(u.searchParams.get('q')||''),group=u.searchParams.get('group')||'all',subgroup=u.searchParams.get('subgroup')||'all',offset=Math.max(0,Number(u.searchParams.get('offset')||0)),limit=Math.min(MAX_LIMIT,Math.max(1,Number(u.searchParams.get('limit')||48))),tokens=q.split(' ').filter(Boolean);const qGroup=queryGroup(q),base=qGroup?c.products.filter(p=>p._g===qGroup):tokens.length?c.products.filter(p=>matchesQuery(p,q)).sort((a,b)=>scoreQuery(b,q)-scoreQuery(a,q)):c.products,categoryCounts=tokens.length?counts(base):c.meta.categoryCounts,groupRows=group==='all'?base:base.filter(p=>p._g===group),subcategoryCounts=subCounts(groupRows),rows=subgroup==='all'?groupRows:groupRows.filter(p=>subFor(p)===subgroup),window=rows.slice(offset,offset+limit*3),models=groupModels(window).slice(0,limit);return{products:models,meta:{...c.meta,categoryCounts,subcategoryCounts,productCount:rows.length,rawProductCount:rows.length,totalProductCount:c.products.length,offset,limit,hasMore:offset+limit<rows.length}}}
function cors(req,res){const o=req.headers.origin;if(o){res.setHeader('Access-Control-Allow-Origin','*')}res.setHeader('Access-Control-Allow-Methods','GET, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type')}function send(res,status,p){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','public, max-age=30, stale-while-revalidate=300');res.end(JSON.stringify(p))}const server=http.createServer(async(req,res)=>{cors(req,res);if(req.method==='OPTIONS'){res.statusCode=204;return res.end()}const u=new URL(req.url||'/','http://localhost');try{if(req.method==='GET'&&u.pathname==='/health'){const p=await getProducts();return send(res,200,{ok:true,ready:!p.meta.warming,warming:!!p.meta.warming,cachedProducts:p.products.length,storeCount:p.meta.storeCount,stores:p.meta.stores,categoryCounts:p.meta.categoryCounts,fetchedAt:p.meta.fetchedAt,tradedoublerConfigured:tradedoublerConfigured()})}if(req.method==='GET'&&u.pathname==='/api/catalog')return send(res,200,page(await getProducts(),u));if(req.method==='GET'&&u.pathname==='/api/search-check'){const p=await getProducts(),qs=['автотовары','auto preces','automotive','инструменты','instrumenti','tools','одежда','apģērbs','clothing','шины','riepas','tires'];return send(res,200,{ok:true,checks:qs.map(q=>{const x=new URL('http://localhost/api/catalog');x.searchParams.set('q',q);x.searchParams.set('limit','1');const r=page(p,x);return{q,count:r.meta.productCount,category:r.products[0]?.cenaRadarCategory||null,sample:r.products[0]?.name||null}})})}return send(res,404,{error:'Not found'})}catch(e){console.error(e);return send(res,500,{error:e.message||'Server error'})}});server.listen(PORT,'0.0.0.0',()=>{console.log(`CenaRadar API ${PORT}; quick boot ${cache.data.products.length}`);setTimeout(()=>void refreshProducts(),100);setInterval(()=>void refreshProducts(),CACHE_MS)});
