import * as cheerio from 'cheerio';
import { decodeMaybeGzip, firstValue, parseCsv } from './feed-utils.mjs';

const UA = 'Mozilla/5.0 (compatible; CenaRadar/1.0; +https://cenaradar.online)';
const CACHE_MS = Number(process.env.MERCHANT_FEED_CACHE_MS || 15 * 60 * 1000);
const SOURCE_WAIT_MS = Number(process.env.MERCHANT_SOURCE_WAIT_MS || 12000);
const cache = new Map();
const inFlight = new Map();
function clean(value=''){return String(value??'').replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim();}
function numberValue(value){const raw=clean(value).replace(/\s/g,'').replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.').replace(/[^0-9.-]/g,'');const n=Number.parseFloat(raw);return Number.isFinite(n)&&n>0?n:null;}
function normalize(value=''){return clean(value).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\p{L}\p{N}]+/gu,' ').trim();}
function matches(product,query){const q=normalize(query);if(!q)return true;const h=normalize([product.name,product.brand,product.model,product.sku,product.mpn,product.ean,product.category,product.description].filter(Boolean).join(' '));return q.split(' ').filter(Boolean).every(t=>h.includes(t));}
function parseSources(){const raw=process.env.MERCHANT_FEEDS_JSON||'';if(!raw)return[];try{const parsed=JSON.parse(raw);const list=Array.isArray(parsed)?parsed:Object.entries(parsed).map(([name,value])=>typeof value==='string'?{name,url:value}:{name,...(value||{})});return list.filter(i=>i&&i.name&&i.url).map(i=>({name:clean(i.name),url:clean(i.url),format:clean(i.format||'auto').toLowerCase(),currency:clean(i.currency||'EUR').toUpperCase()}));}catch(error){console.error(`MERCHANT_FEEDS_JSON is invalid: ${error instanceof Error?error.message:'unknown error'}`);return[];}}
async function fetchFeedBuffer(url){let lastError;for(const timeout of[45000,90000]){try{const response=await fetch(url,{headers:{'User-Agent':UA,Accept:'application/xml,text/xml,text/csv,application/json,text/plain,*/*','Accept-Encoding':'gzip, deflate, br',Connection:'keep-alive'},redirect:'follow',signal:AbortSignal.timeout(timeout)});if(!response.ok)throw new Error(`HTTP ${response.status}`);return Buffer.from(await response.arrayBuffer());}catch(error){lastError=error;console.warn(`Merchant feed fetch retry: ${new URL(url).hostname}, timeout=${timeout}ms, error=${error instanceof Error?error.message:'unknown error'}`);}}throw lastError||new Error('Feed download failed');}
function field(row,names){return clean(firstValue(row,names));}
function stockValue(value){const raw=clean(value);if(!raw)return'1';if(/out.?of.?stock|unavailable|nav pieej|izpārdots|^false$|^no$/i.test(raw))return'0';const numeric=Number.parseFloat(raw.replace(',','.'));if(Number.isFinite(numeric))return numeric>0?'1':'0';return'1';}
function mapCsvRow(row,source,index){const name=field(row,['name','Name','product_name','Product Name','title','Title']);const price=numberValue(field(row,['price','Price','search_price','store_price','sale_price','current_price']));const url=field(row,['merchant_deep_link','sourceProductUrl','productURL','product_url','url','URL','link','Link']);if(!name||!price||!url)return null;const model=field(row,['model','Model','model_number']);const mpn=field(row,['mpn','MPN','manufacturer_part_number']);const ean=field(row,['ean','EAN','gtin','GTIN','upc','UPC','isbn','ISBN']);const sku=field(row,['sku','SKU','merchant_product_id','product_id'])||mpn||ean||model;return{id:`${source.name}:${field(row,['id','product_id','productId'])||ean||mpn||sku||index}`,name,sku,model,mpn,ean,description:field(row,['description','Description','product_short_description','short_description']).slice(0,360),price,compareAtPrice:numberValue(field(row,['old_price','product_price_old','rrp_price','compare_at_price'])),currency:field(row,['currency','Currency','currencyISOCode'])||source.currency,image:field(row,['imageURL','image_url','merchant_image_url','aw_image_url','image','Image','picture']),url,merchantUrl:url,merchant:source.name,delivery:field(row,['delivery','delivery_cost','shipping']),brand:field(row,['brand','brand_name','Brand','manufacturer','Manufacturer']),inStock:stockValue(field(row,['in_stock','stock_status','availability','available','stock'])),priceSource:'merchant_feed',lastUpdated:field(row,['last_updated','updated_at','modifiedDate'])||null,category:field(row,['category_full','category','category_name','merchant_category','product_type'])};}
function parseCsvFeed(text,source){return parseCsv(text).map((r,i)=>mapCsvRow(r,source,i)).filter(Boolean);}
function nodeText(node,names){for(const name of names){const found=node.find(name).first();if(found.length){const value=clean(found.text()||found.attr('value')||found.attr('href')||'');if(value)return value;}const attr=node.attr(name);if(attr)return clean(attr);}return'';}
function parseXmlFeed(text,source){const $=cheerio.load(text,{xmlMode:true});let nodes=$('product');if(!nodes.length)nodes=$('item');if(!nodes.length)nodes=$('offer');if(!nodes.length)nodes=$('SHOPITEM');if(!nodes.length)nodes=$('entry');if(!nodes.length){const root=$.root().children().first();const children=root.children();if(children.length)nodes=children;}const products=[];nodes.each((index,el)=>{const node=$(el);const name=nodeText(node,['name','title','product_name','NAME','PRODUCTNAME','product']);const price=numberValue(nodeText(node,['price','search_price','store_price','sale_price','PRICE','PRICE_VAT','price_vat']));const url=nodeText(node,['merchant_deep_link','sourceProductUrl','productURL','product_url','url','link','URL','PRODUCT','product_link']);if(!name||!price||!url)return;const model=nodeText(node,['model','model_number','MODEL']);const mpn=nodeText(node,['mpn','manufacturer_part_number','MPN']);const ean=nodeText(node,['ean','gtin','upc','isbn','EAN']);const sku=nodeText(node,['sku','merchant_product_id','product_id','ITEM_ID','id'])||mpn||ean||model;products.push({id:`${source.name}:${sku||index}`,name,sku,model,mpn,ean,description:nodeText(node,['description','product_short_description','short_description','DESCRIPTION']).slice(0,360),price,compareAtPrice:numberValue(nodeText(node,['old_price','product_price_old','rrp_price','compare_at_price','OLDPRICE'])),currency:nodeText(node,['currency','currencyISOCode','CURRENCY'])||source.currency,image:nodeText(node,['imageURL','image_url','merchant_image_url','image','picture','IMGURL','IMAGE']),url,merchantUrl:url,merchant:source.name,delivery:nodeText(node,['delivery','delivery_cost','shipping','DELIVERY']),brand:nodeText(node,['brand','brand_name','manufacturer','MANUFACTURER']),inStock:stockValue(nodeText(node,['in_stock','stock_status','availability','available','stock','STOCK'])),priceSource:'merchant_feed',lastUpdated:nodeText(node,['last_updated','updated_at','modifiedDate'])||null,category:nodeText(node,['category_full','category','category_name','merchant_category','product_type','CATEGORYTEXT','CATEGORY'])});});return products;}
function flattenJsonProducts(value){if(!value)return[];if(Array.isArray(value))return value;for(const key of['products','items','offers','data','results'])if(Array.isArray(value?.[key]))return value[key];return[];}
function parseJsonFeed(text,source){return flattenJsonProducts(JSON.parse(text)).map((r,i)=>mapCsvRow(r,source,i)).filter(Boolean);}
async function loadSourceNow(source){const buffer=await fetchFeedBuffer(source.url);const text=decodeMaybeGzip(buffer);const trimmed=text.trimStart();const format=source.format==='auto'?(trimmed.startsWith('<')?'xml':trimmed.startsWith('{')||trimmed.startsWith('[')?'json':'csv'):source.format;let products;if(format==='xml')products=parseXmlFeed(text,source);else if(format==='json')products=parseJsonFeed(text,source);else products=parseCsvFeed(text,source);cache.set(source.url,{time:Date.now(),products});console.log(`Merchant feed loaded: ${source.name}=${products.length}, bytes=${buffer.length}`);return products;}
async function loadSource(source){const existing=cache.get(source.url);if(existing&&Date.now()-existing.time<CACHE_MS)return existing.products;if(inFlight.has(source.url))return inFlight.get(source.url);const task=loadSourceNow(source).catch(error=>{console.error(`Merchant feed failed: ${source.name}: ${error instanceof Error?error.message:'unknown error'}`);throw error;}).finally(()=>inFlight.delete(source.url));inFlight.set(source.url,task);return task;}
function waitForSource(source){const existing=cache.get(source.url);if(existing)return Promise.resolve(existing.products);const task=loadSource(source);return Promise.race([task,new Promise((_,reject)=>setTimeout(()=>reject(new Error(`Background refresh still running after ${SOURCE_WAIT_MS}ms`)),SOURCE_WAIT_MS))]);}
export function configuredMerchantNames(){return parseSources().map(s=>s.name);}
export async function searchConfiguredMerchantFeeds(query,limitPerSource=30){const sources=parseSources();if(!sources.length)return{products:[],sources:[]};const settled=await Promise.allSettled(sources.map(s=>waitForSource(s)));const products=[];const statuses=[];settled.forEach((result,index)=>{const source=sources[index];if(result.status==='fulfilled'){const found=result.value.filter(p=>matches(p,query)).slice(0,limitPerSource);products.push(...found);statuses.push({name:source.name,ok:true,count:found.length,total:result.value.length,mode:'feed'});}else{const cached=cache.get(source.url)?.products||[];if(cached.length){const found=cached.filter(p=>matches(p,query)).slice(0,limitPerSource);products.push(...found);statuses.push({name:source.name,ok:true,count:found.length,total:cached.length,mode:'cached_feed'});}else statuses.push({name:source.name,ok:false,count:0,total:0,mode:'background_feed',error:result.reason instanceof Error?result.reason.message:'Feed refresh pending'});}});return{products,sources:statuses};}
