import * as cheerio from 'cheerio';
import { decodeMaybeGzip, firstValue, parseCsv } from './feed-utils.mjs';

const UA='Mozilla/5.0 (compatible; CenaRadar/1.0; +https://cenaradar.online)';
const CACHE_MS=Number(process.env.MERCHANT_FEED_CACHE_MS||15*60*1000);
const SOURCE_WAIT_MS=Number(process.env.MERCHANT_SOURCE_WAIT_MS||12000);
const HARD_FETCH_MS=Number(process.env.MERCHANT_HARD_FETCH_MS||60000);
const cache=new Map(),inFlight=new Map();
const clean=(v='')=>String(v??'').replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim();
function numberValue(v){const r=clean(v).replace(/\s/g,'').replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.').replace(/[^0-9.-]/g,'');const n=Number.parseFloat(r);return Number.isFinite(n)&&n>0?n:null;}
const normalize=(v='')=>clean(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\p{L}\p{N}]+/gu,' ').trim();
function matches(p,q){q=normalize(q);if(!q)return true;const h=normalize([p.name,p.brand,p.model,p.sku,p.mpn,p.ean,p.category,p.description].filter(Boolean).join(' '));return q.split(' ').filter(Boolean).every(t=>h.includes(t));}
function parseSources(){const raw=process.env.MERCHANT_FEEDS_JSON||'';if(!raw)return[];try{const x=JSON.parse(raw);const a=Array.isArray(x)?x:Object.entries(x).map(([name,v])=>typeof v==='string'?{name,url:v}:{name,...(v||{})});const out=a.filter(i=>i?.name&&i?.url).map(i=>({name:clean(i.name),url:clean(i.url),format:clean(i.format||'auto').toLowerCase(),currency:clean(i.currency||'EUR').toUpperCase()}));const approved=[{name:'Pirkums.lv',url:'https://www.pirkums.lv/export/salidzini.xml',format:'xml',currency:'EUR'}];for(const s of approved)if(!out.some(x=>x.url===s.url||normalize(x.name)===normalize(s.name)))out.push(s);return out;}catch(e){console.error(`MERCHANT_FEEDS_JSON is invalid: ${e instanceof Error?e.message:'unknown error'}`);return[];}}
async function fetchFeedBuffer(url){let last;for(let attempt=1;attempt<=3;attempt++){const c=new AbortController();const timer=setTimeout(()=>c.abort(),HARD_FETCH_MS);try{const r=await fetch(url,{headers:{'User-Agent':UA,Accept:'application/xml,text/xml,text/csv,application/json,text/plain,*/*','Accept-Language':'lv,en;q=0.8','Cache-Control':'no-cache'},redirect:'follow',signal:c.signal});if(r.ok)return Buffer.from(await r.arrayBuffer());last=new Error(`HTTP ${r.status}`);if(![403,408,429,500,502,503,504].includes(r.status))throw last;}catch(e){last=e;}finally{clearTimeout(timer);}if(attempt<3)await new Promise(r=>setTimeout(r,attempt*1200));}throw last||new Error('Feed fetch failed');}
const field=(r,n)=>clean(firstValue(r,n));
function stockValue(v){const r=clean(v);if(!r)return'1';if(/out.?of.?stock|unavailable|nav pieej|izpārdots|^false$|^no$/i.test(r))return'0';const n=Number.parseFloat(r.replace(',','.'));return Number.isFinite(n)?(n>0?'1':'0'):'1';}
function mapRow(r,s,i){const name=field(r,['name','Name','product_name','Product Name','title','Title']),price=numberValue(field(r,['price','Price','search_price','store_price','sale_price','current_price'])),url=field(r,['merchant_deep_link','sourceProductUrl','productURL','product_url','url','URL','link','Link']);if(!name||!price||!url)return null;const model=field(r,['model','Model','model_number']),mpn=field(r,['mpn','MPN','manufacturer_part_number']),ean=field(r,['ean','EAN','gtin','GTIN','upc','UPC','isbn','ISBN']),sku=field(r,['sku','SKU','merchant_product_id','product_id'])||mpn||ean||model;return{id:`${s.name}:${field(r,['id','product_id','productId'])||ean||mpn||sku||i}`,name,sku,model,mpn,ean,description:field(r,['description','Description','product_short_description','short_description']).slice(0,360),price,compareAtPrice:numberValue(field(r,['old_price','product_price_old','rrp_price','compare_at_price'])),currency:field(r,['currency','Currency','currencyISOCode'])||s.currency,image:field(r,['imageURL','image_url','merchant_image_url','aw_image_url','image','Image','picture']),url,merchantUrl:url,merchant:s.name,delivery:field(r,['delivery','delivery_cost','shipping']),brand:field(r,['brand','brand_name','Brand','manufacturer','Manufacturer']),inStock:stockValue(field(r,['in_stock','stock_status','availability','available','stock'])),priceSource:'merchant_feed',lastUpdated:field(r,['last_updated','updated_at','modifiedDate'])||null,category:field(r,['category_full','category','category_name','merchant_category','product_type'])};}
const nodeText=(n,names)=>{for(const x of names){const f=n.find(x).first();if(f.length){const v=clean(f.text()||f.attr('value')||f.attr('href')||'');if(v)return v;}const a=n.attr(x);if(a)return clean(a);}return'';};
function parseXml(text,s){const $=cheerio.load(text,{xmlMode:true});let nodes=$('product,item,offer,SHOPITEM,entry');if(!nodes.length){const c=$.root().children().first().children();if(c.length)nodes=c;}const out=[];nodes.each((i,e)=>{const n=$(e),name=nodeText(n,['name','title','product_name','NAME','PRODUCTNAME','product']),price=numberValue(nodeText(n,['price','search_price','store_price','sale_price','PRICE','PRICE_VAT','price_vat'])),url=nodeText(n,['merchant_deep_link','sourceProductUrl','productURL','product_url','url','link','URL','PRODUCT','product_link']);if(!name||!price||!url)return;const model=nodeText(n,['model','model_number','MODEL']),mpn=nodeText(n,['mpn','manufacturer_part_number','MPN']),ean=nodeText(n,['ean','gtin','upc','isbn','EAN']),sku=nodeText(n,['sku','merchant_product_id','product_id','ITEM_ID','id'])||mpn||ean||model;out.push({id:`${s.name}:${sku||i}`,name,sku,model,mpn,ean,description:nodeText(n,['description','DESCRIPTION']).slice(0,360),price,currency:nodeText(n,['currency','CURRENCY'])||s.currency,image:nodeText(n,['imageURL','image_url','image','picture','IMGURL','IMAGE']),url,merchantUrl:url,merchant:s.name,brand:nodeText(n,['brand','manufacturer','MANUFACTURER']),inStock:stockValue(nodeText(n,['availability','stock','STOCK'])),priceSource:'merchant_feed',category:nodeText(n,['category','CATEGORYTEXT','CATEGORY'])});});return out;}
async function loadNow(s){const b=await fetchFeedBuffer(s.url),text=decodeMaybeGzip(b),t=text.trimStart(),f=s.format==='auto'?(t.startsWith('<')?'xml':t.startsWith('{')||t.startsWith('[')?'json':'csv'):s.format;let p;if(f==='xml')p=parseXml(text,s);else if(f==='json'){const j=JSON.parse(text),a=Array.isArray(j)?j:(j.products||j.items||j.offers||j.data||j.results||[]);p=a.map((r,i)=>mapRow(r,s,i)).filter(Boolean);}else p=parseCsv(text).map((r,i)=>mapRow(r,s,i)).filter(Boolean);cache.set(s.url,{time:Date.now(),products:p});console.log(`Merchant feed loaded: ${s.name}=${p.length}, bytes=${b.length}`);return p;}
function loadSource(s){const c=cache.get(s.url);if(c&&Date.now()-c.time<CACHE_MS)return Promise.resolve(c.products);if(inFlight.has(s.url))return inFlight.get(s.url);const task=loadNow(s).catch(e=>{console.error(`Merchant feed failed: ${s.name}: ${e instanceof Error?e.message:'unknown error'}`);return cache.get(s.url)?.products||[];}).finally(()=>inFlight.delete(s.url));inFlight.set(s.url,task);return task;}
export function configuredMerchantNames(){return parseSources().map(s=>s.name);}
export async function searchConfiguredMerchantFeeds(query,limitPerSource=30){const sources=parseSources();if(!sources.length)return{products:[],sources:[]};const results=await Promise.all(sources.map(async s=>{const cached=cache.get(s.url)?.products||[];if(cached.length){void loadSource(s);return{source:s,products:cached,mode:'cached_feed'};}const task=loadSource(s);const p=await Promise.race([task,new Promise(resolve=>setTimeout(()=>resolve(null),SOURCE_WAIT_MS))]);return{source:s,products:Array.isArray(p)?p:[],mode:Array.isArray(p)&&p.length?'feed':'background_feed'};}));const products=[],statuses=[];for(const r of results){const found=r.products.filter(p=>matches(p,query)).slice(0,limitPerSource);products.push(...found);statuses.push({name:r.source.name,ok:r.products.length>0,count:found.length,total:r.products.length,mode:r.mode});}return{products,sources:statuses};}
